### PR TITLE
Upgrade to use bootstrap version 5.1

### PR DESCRIPTION
**Pull request by plastikfan**
Hi Evan,

I know its been a while since I first looked at your template, I've been around the houses a bit and have come full circle. I want to build documentation based upon version 5.1 of bootstrap. I was initially put off from going ahead using BS-4, because I didn't want to base my documenation on legacy BS, not knowing if it was possible to update your template to BS-5. After a few experiments, I got this to work, and it was a bit easier than I had envisaged apart from a little caveat explained further below.

So what I have done is:

1) update the bootstrap assets to their latest versions (5.1)
2) The navbar contents was not right aligned so I changed mr-auto in one of the containers to use ms-auto instead. This shifted the contents including the search box to the right
3) changed jumbotron to use container-fluid instead of jumbotron

I also wanted to remove jQuery, because now BS-5 no longer mandates its presence and has been removed. I initially tried to remove jQuery but this broke the lunr search. On closer inspection, I realised that the lunr functionality was using jQuery:

___template/lunr-js.html___
```javascript
function lunr_search () {
  var resultdiv = $('#results');
  var query = $('input#search').val();//.toLowerCase();
  /* basic search that supports operators */
  var result = idx.search(query); 
```

PS: I'm still just learning the client side/broswer tech stack, so I still stumble on relatively simple issues like this one.

I noticed that the:

>  $('#results');

was the jquery that was broken. The removal of the jQuery script entry broke the search. However, I didnt know how to fix. I just assumed that

> var resultdiv = $('#results');
> var query = $('input#search').val();

should be replaced with

> var resultdiv = document.getElementById('results');
> var query = document.getElementById('input#search');

but this didnt work either.

I also attempted to update lunr with the latest version and updated the cdn link, perhaps this was the cause of me not being able to get this to work, the __lunr__ identifier was undefined; probably to an incorrectly specified script reference. But even without updating lunr and leaving that as it was, using the _getElementById_ instead of the jQuery $ notation I saw this error in the console:

```
Uncaught TypeError: e is null
    QueryLexer http://127.0.0.1:4000/assets/lib/lunr.min.js:6
    QueryParser http://127.0.0.1:4000/assets/lib/lunr.min.js:6
    search http://127.0.0.1:4000/assets/lib/lunr.min.js:6
    query http://127.0.0.1:4000/assets/lib/lunr.min.js:6
    search http://127.0.0.1:4000/assets/lib/lunr.min.js:6
    lunr_search http://127.0.0.1:4000/search.html?q=cat:139
    <anonymous> http://127.0.0.1:4000/search.html?q=cat:174
    jQuery 13
```

I am guessing I've passed in the incorrect item into _getElementById_, but I dont know what it should be.

So I gave up and left the original functionality, so as to not break the template. The important part was the upgrade to BS-5. 

It would be great if you could perform the required fixes to remove jQuery and fix up the search functionality to not use it. I would be interested to see how this problem would be fxed for my own knowledge 🙏

### CODE REVIEW

**Comment by evanwill** [comment]
@plastikfan sorry I haven't had a chance to look at this yet! I appreciate the PR and will get to it before toooo long, thank you.

**Comment by plastikfan** [comment]
That's no problem. I've been doing doing some research and I now realise why I couldn't get the lunr to search properly. I've learnt that getElementById simply returns a DOM object where as $() returns a jQuery object. So we're dealing with different types and thus needs different code. 

However, I've been doing more research and learning of bootstrap/Jekyll/react and I've also learnt that to a large degree Jekyll has been superseded by Hugo which many people are using now. But then I also learnt that you can build a static website with Gatsby. I have been commissioned to do some work that needs more than just a static website, so to keep my learning curve from spiralling out of control, it's probably best just to stick with Gatsby so I can build my documentation using this stack and also use it for client work. This means I probably won't need to use your template. But I learnt a great deal from experimenting with your template and Jekyll so I thank you again for creating those very informative videos. Im sure there will be others that will appreciate the upgrade of the template to bootstrap 5 though. Cheers.

**Comment by evanwill** [comment]
thanks @plastikfan, hope your work is going well. Gatsby is cool-->but learning curve seems higher than Jekyll for getting started really quick in a workshop setting and having a website quickly hosted on github, which is the purpose of this template. 

I am going to close this PR, because rather than pulling this in, I decided to keep bootstrap-template at bootstrap version 4.6, and created a slightly different version in a new template repository: bootstrap5-template, https://github.com/thecdil/bootstrap5-template

Thanks again!

**Comment by plastikfan** [comment]
Great thanks Evan. I learnt a lot from using this template so I appreciate your efforts. And yeah I agree with you about the learning curve about alternative options but it's a hit I'm prepared to take given my ultimate goals. Cheers

**Pull request closed without merging**
